[workspace]
members = [
    "matrix",
    "gettime",
    "proc_switch",
    "thread_switch",
    "coroutine_switch",
    "coroutine_switch2",
    "user_thread_switch",
    "user_thread_switch2",
    "coroutine_overhead",
    "coroutine_overhead2",
]